### ISSUE TITLE
Latest update breaks everything

### ISSUE THREAD

**Issue by deltaflyer4747** [esnya/UdonRadioCommunication#18]
after importing SF-1 + COM prefab
receiver entity:
Assets/UdonRadioCommunication/Scripts/Receiver.cs(8,4): System.Exception: User type Receiver could not be found
transceiver entity:
Assets/UdonRadioCommunication/Scripts/Transceiver.cs(12,4): System.Exception: User type Transceiver could not be found

**Comment by OrwinRaqoon** [comment]
I'm getting the same thing, first time install.  Beta 5.0 seems to be working, using that instead.
