### ISSUE TITLE
Frequency precision issue still not fixed

### ISSUE THREAD

**Issue by deltaflyer4747** [esnya/UdonRadioCommunication#19]
Issue in https://github.com/esnya/UdonRadioCommunication/issues/16 still persists with latest release.

UdonRadioCommunication:

FrequencyGap = 0.025
MinFrequency = 118
MaxFrequency = 136
FrequencyStep = 0.025
FastFrequencyStep = 1

Problem is not within receivers reading frequency incorrect, but with transceiver setting incorrect frequency and floating point imprecission & processing in unity. It shows on debug screen as well and there is no receiver.

in previous post i posted transceiver.cs where i modified original

`Frequency = f > maxFrequency ? minFrequency : (f < minFrequency ? maxFrequency : f);`
to this, which fixes the issue
`Frequency = Mathf.Round(((f > maxFrequency ? minFrequency : (f < minFrequency ? maxFrequency : f)) * Mathf.Pow(10, frequencyPrecision))) / Mathf.Pow(10, frequencyPrecision);`

**Comment by esnya** [comment]
frequencyGap must be smaller than half of frequencyStep. Try to set 0.01 in this case.
