### ISSUE TITLE
Encountered exception while upgrading prefab

### ISSUE THREAD

**Issue by Bjorn0411** [esnya/UdonRadioCommunication#29]
Unity 2019.4.31f1
Installed via new VRCCC (VRChat Creator Companion)
VRCSDK - Base 3.0.8
VRCSDK - Worlds 3.0.8
UdonSharp - 1.0.1
VRChat Client Sim 1.1.4

RadioAsset - tested with Beta16/Beta15/4.4.1

The error I get in the console:
[UdonSharp] Hit exception while attempting to upgrade scene behaviours: System.InvalidOperationException: Cannot run serialization on U# behaviour 'UdonRadioCommunicationDemo (URC.UdonRadioCommunication)' with outdated behaviour version, wait until program assets have compiled.
  at UdonSharpEditor.UdonSharpEditorUtility.CopyUdonToProxy (UdonSharp.UdonSharpBehaviour proxy, UdonSharpEditor.ProxySerializationPolicy serializationPolicy) [0x00045] in D:\Unity\CaveAdventureWorld\Library\PackageCache\com.vrchat.udonsharp@26d6812704\Editor\UdonSharpEditorUtility.cs:987 
  at UdonSharpEditor.UdonSharpEditorUtility.UpgradeSceneBehaviours (System.Collections.Generic.IEnumerable`1[T] behaviours) [0x002f9] in D:\Unity\CaveAdventureWorld\Library\PackageCache\com.vrchat.udonsharp@26d6812704\Editor\UdonSharpEditorUtility.cs:553 
  at UdonSharpEditor.UdonSharpEditorManager.RunAllUpgrades () [0x0002b] in D:\Unity\CaveAdventureWorld\Library\PackageCache\com.vrchat.udonsharp@26d6812704\Editor\UdonSharpEditorManager.cs:1612 
UnityEngine.Debug:LogError (object)
UdonSharp.UdonSharpUtils:LogError (object) (at Library/PackageCache/com.vrchat.udonsharp@26d6812704/Editor/UdonSharpUtils.cs:316)
UdonSharpEditor.UdonSharpEditorManager:RunAllUpgrades () (at Library/PackageCache/com.vrchat.udonsharp@26d6812704/Editor/UdonSharpEditorManager.cs:1616)
UdonSharpEditor.UdonSharpEditorManager:OnChangePlayMode (UnityEditor.PlayModeStateChange) (at Library/PackageCache/com.vrchat.udonsharp@26d6812704/Editor/UdonSharpEditorManager.cs:693)
UnityEditor.EditorApplication:Internal_PlayModeStateChanged (UnityEditor.PlayModeStateChange)
VRC.SDK3.Editor.Builder.VRCWorldAssetExporter:LaunchSceneBlueprintUploader ()
VRC.SDK3.Editor.Builder.VRCWorldBuilder:UploadLastExportedSceneBlueprint ()
VRC.SDK3.Editor.Builder.VRCWorldBuilder:ExportSceneAndPrepareForUpload ()
VRC.SDK3.Editor.Builder.VRCWorldBuilder:ExportAndUploadSceneBlueprint ()
VRC.SDKBase.Editor.VRC_SdkBuilder:ExportAndUploadSceneBlueprint ()
VRC.SDK3.Editor.VRCSdkControlPanelWorldBuilder3:OnGUIScene () (at Library/PackageCache/com.vrchat.worlds@cdd31e9733/Editor/VRCSDK/SDK3/VRCSdkControlPanelWorldBuilder3.cs:252)
VRC.SDKBase.Editor.VRCSdkControlPanelWorldBuilder:ShowBuilder () (at Library/PackageCache/com.vrchat.base@cdd31e9733/Editor/VRCSDK/Dependencies/VRChat/ControlPanel/VRCSdkControlPanelWorldBuilder.cs:130)
VRC.SDK3.Editor.VRCSdkControlPanelWorldBuilder3:ShowBuilder () (at Library/PackageCache/com.vrchat.worlds@cdd31e9733/Editor/VRCSDK/SDK3/VRCSdkControlPanelWorldBuilder3.cs:43)
VRCSdkControlPanel:ShowBuilders () (at Library/PackageCache/com.vrchat.base@cdd31e9733/Editor/VRCSDK/Dependencies/VRChat/ControlPanel/VRCSdkControlPanelBuilder.cs:329)
VRCSdkControlPanel:OnGUI () (at Library/PackageCache/com.vrchat.base@cdd31e9733/Editor/VRCSDK/Dependencies/VRChat/ControlPanel/VRCSdkControlPanel.cs:214)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)

This happens as soon as I put any of your assets into the scene. Just having your pack installed still allows me to publish.

I AM able to do build & test, where your assets work perfectly fine, this only occurs when trying to press build and publish for windows.
My guess is that im using a version of UdonSharp thats changed something. Maybe the one from the VRCCC is special?

Lemme know if theres any additional info you need! When I was testing them through Build & Test they were amazing! _Exactly_ what I was looking for for my world!

**Comment by esnya** [comment]
The logs indicate that U# assets are not compiled. If you have not installed UdonRadioComunication with the git URL, `Compile All UdonSharp Programs` may solve the problem. Otherwise, Unity will get fail because it cannot rewrite the assets.

If logs shows prefabs are broken. Then you can build system without any Prefabs, they will maybe works.

----

This project is still being developed with UdonSharp 0.x. **U# 0.x and 1.0 are not compatible**. The compiled program should not even work as is. We also observe that most Prefabs are broken. I believe this is due to incomplete conversion on the U# side.

Whenever I install with VCC, it is always installs 1.0. However, VCC is still a test version. The only other way to get 1.0 is private beta, and while it is possible to fully migrate to VCC, I don't know when that should be done.

Finally, I would like to inform you that the [feature/usharp-1.0](https://github.com/esnya/UdonRadioCommunication/tree/feature/usharp-1.0) branch exists. This is an experimental branch. So I'cant promise you to it works completely.

**Comment by Bjorn0411** [comment]
Thank you for the thorough response! 

"Compile All UdonSharp Programs may solve the problem."
as far as I could tell, this did nothing at all.

"the [feature/usharp-1.0](https://github.com/esnya/UdonRadioCommunication/tree/feature/usharp-1.0) branch exists."
This however, worked perfectly! I apologize for missing it, I did go through the branches but my eyes must have accidentally rolled off of it.

Thank you for the powerful tool. It is perfect for my exploration-focused world. Great work!
