### ISSUE TITLE
Single line code error fresh install.

### ISSUE THREAD

**Issue by HikariMiru** [esnya/UdonRadioCommunication#8]
Assets\UdonRadioCommunication\Scripts\UdonRadioCommunication.cs(39,16): error CS0246: The type or namespace name 'TextMeshPro' could not be found (are you missing a using directive or an assembly reference?)

**Comment by esnya** [comment]
What versions of UdonRadioCommunication, UdonSharp, VRChat SDK and Unity did you import?
TextMeshPro may be installed by default, or you can install it manually from the package manager.

**Comment by HikariMiru** [comment]
The laest ver.

**Comment by esnya** [comment]
> The laest ver.
It does not contain any information for debugging.

I have no idea when you installed them or which branch you are using.

**Comment by esnya** [comment]
I tested the same version and did not get any errors...

TextMeshPro has been updated to a major version since the beginning of this year. Perhaps this may have an effect.
Old Unity projects contain old TMPs, so you should update to the latest version from the package manager.
Please tell me which version of TMP are you used and after updated.

**Comment by selgood** [comment]
I have TMP v.2.1.6 installed. I also went and tried to install te Radio package on a fresh project and got the exact same error.

**Comment by selgood** [comment]
> 
> 
> I have TMP v.2.1.6 installed. I also went and tried to install te Radio package on a fresh project and got the exact same error.

I went and got the latest Beta release for the project and it seems to be working now.

**Comment by esnya** [comment]
Hmmm... Thanks to test.

I'll release next version from beta soon. Please use beta releases until update...

**Comment by esnya** [comment]
4.0.0 rleased
